= Cahier de tests V1

Si vous remarquez qu'il y a des choses à modifier ou à rajouter, n'hésitez pas.

== Présentation du projet

=== Objectifs 

=== Responsabilités

== Périmètre et environnement des tests

=== Cadre de tests

=== Equipes concernées

== Liste des tests

Une liste de tests, comme son nom l'indique, permet de décrire les différentes actions à conduire afin de réaliser les futurs tests.
Ces listes de tests facilitent ainsi la compréhension et la clarté des actions à mener mais également de faciliter la qualification des problèmes rencontrés au cours de la réalisation d'une action et donc, d'une manière plus générale, de la gestion de celles-ci.

.Développement des cas d'utilisation de la V1

|===
|N° |Acteurs |Actions à réaliser |Attendus des actions sur l'application |Validité

|1
|Chef d'Agence
|Gérer les employés (guichetiers et lui-même)
|
|

|2
.4+<.>|Guichetier
|Créditer ou débiter un compte
|• Doit pouvoir être affiché dans une liste des opérations effectuées (listview) ; +

 • Ne doit pas pouvoir être crédité ou débité d'une somme négative. + 
 → _Message d'erreur "Veuillez renseigner une valeur positive pour effectuer votre transaction." (dans une liste ou sous forme de pop-up) ;_ +

 • Ne doit pas pouvoir être débité d'une somme supérieure à un plafond éventuellement défini. + 
 → _Message d'erreur "Veuillez renseigner une valeur inférieure au plafond défini." (dans une liste ou sous forme de pop-up)_
|

|3
|Créer un compte à partir d'informations complémentaires
|• Doit pouvoir être visible par le créateur du compte ainsi que le chef d'agence (proposée en tant qu'option pour celui-ci).

 • Ne doit pas renseigner des informations erronées (message possédant des caractères spéciaux ou ne respectant pas le type attendu). +
 → _Message d'erreur "Veuillez vérifiez que vos informations renseignées soient valides." (dans une liste ou sous forme de pop-up) ;_ +

 • Ne doit pas pouvoir être crée une seconde fois. +
 → _Message d'erreur "Le compte que vous avez renseigné existe déjà." (dans une liste ou sous forme de pop-up)_
|

|4
|Effectuer un virement de compte à compte
|• Doit pouvoir être affiché en tant que message dans une liste pour l'émetteur et le bénéficiaire (optionnel pour celui-ci, étant déjà visible dans ses comptes).
 
 • Ne doit pas pouvoir être crédité ou débité d'une somme négative. + 
 → _Message d'erreur "Veuillez renseigner une valeur positive pour effectuer votre virement." (dans une liste ou sous forme de pop-up) ;_ +

 • Ne doit pas pouvoir effectuer le virement d'une somme supérieure à un plafond éventuellement défini. + 
 → _Message d'erreur "Veuillez renseigner une valeur inférieure au plafond défini." (dans une liste ou sous forme de pop-up)_
 
 • Ne doit pas pouvoir réaliser le virement vers un compte clôturé ou n'existant pas.
 → _Message d'erreur "Veuillez choisir un compte valide." (dans une liste ou sous forme de pop-up)_
|

|5
|Clôturer un compte
|
|
