= Cahier de tests V1

Si vous remarquez qu'il y a des choses à modifier ou à rajouter, n'hésitez pas.

== Présentation du projet

=== Objectifs 

=== Responsabilités

== Périmètre et environnement des tests

=== Cadre de tests

=== Equipes concernées

== Liste des tests

Une liste de tests, comme son nom l'indique, permet de décrire les différentes actions à conduire afin de réaliser les futurs tests.
Ces listes de tests facilitent ainsi la compréhension et la clarté des actions à mener mais également de faciliter la qualification des problèmes rencontrés au cours de la réalisation d'une action et donc, d'une manière plus générale, de la gestion de celles-ci.

.Développement des cas d'utilisation de la V1

|===
|N° |Acteurs |Actions à réaliser |Attendus des actions sur l'application |Validité

|1
|Chef d'Agence
|Gérer les employés (guichetiers et lui-même)
|
|

|2
.4+<.>|Guichetier
|Créditer ou débiter un compte
|• Doit pouvoir être affiché dans une liste des opérations effectuées (listview) ; +
 • Ne doit pas pouvoir être crédité ou débité d'une somme négative + 
 → Message d'erreur "Veuillez renseigner une valeur positive pour effectuer votre transaction." (dans la liste ou sous forme de pop-up) ; +
 • Ne doit pas pouvoir être débité d'une somme supérieure à un plafond éventuellement défini + 
 → Message d'erreur "Veuillez renseigner une valeur inférieure au plafond défini." (dans la liste ou sous forme de pop-up) ;
|

|3
|Créer un compte
|Doit pouvoir créer son compte à partir d'informations complémentaires. Est visible par le chef d'agence. / Ne doit pas pouvoir être crée une seconde fois, sinon, erreur à l'affichage (sous forme de pop-up ou autre)
|

|4
|Effectuer un virement de compte à compte
|
|

|5
|Clôturer un compte
|
|
