= SAÉ 01-05
= CDCU V1
Editée le 29/03/2022
Equipe composée des membres suivants : 

-> Louis Yvelin

-> Victor Thompson

-> Mickael Fernandez

-> Nicolas Sacilotto

--TO DO--

Etablir un sommaire

Présenter le sujet ( Contexte, objectif , à quel pb il répond )

Faire une analayse de l'existant ( BD ) 

Analyser les tâches techniques et organisationelles (voir le sujet )

--DO TO--



= Contexte 

La banque DailyBank souhaite développer une application JAVA-Oracle de gestion des comptes clients pour remplacer plusieurs outils obsolètes. Ce développement s’inscrit dans le cadre de la restructuration de ses services bancaires et l’application sera déployée dans les 100 agences que compte son réseau. Nous travaillerons à partir d’une application existante « Daily Bank » qu’il faudra adapter aux nouveaux besoins de la banque.

== Description de l'application
L’application permet de gérer des comptes bancaires de dépôt pour des clients préalablement créés. Elle permet de débiter, créditer un compte soit par virement c’est à dire un échange d’argent entre deux comptes distincts mais domiciliés dans le réseau bancaire, soit par une personne physique se présentant devant un guichet.
