
= SAÉ 01-05

Editée le 29/03/2022

_Groupe 4A02 :_


MAJ le 08/05/2022:

=== Tâches à faire 

==== GPO :

- [ ] Créer la documentation technique de la V0
- [x] Créer la documentation utilisateur de la V0
- [ ] Rédiger la documentation technique et la documentation utilisateur V1
- [ ] Rédiger le cahier de test V2
- [x] Mettre à jour le GANTT et les issues

*Lien vers le CDCU V3 :* https://github.com/IUT-Blagnac/sae2022-bank-4a2/blob/main/V3/CDCU%20V3.adoc[__Cliquer ici__]

|===
|MEMBRES :
|_Louis Yvelin_
|_Victor Thompson_
|_Mickael Fernandez_
|_Nicolas Sacilotto_
|===

=== Prise en compte des commentaires

- Ajustement du sommaire numéroté
- Fautes de frappes
- Infos essentielles (équipe, date, nom projet, clients)
- Dates de livraison
- Doc. technique

=== Commentaires

Livraison CDCU V3 : +
0,5/2	manque équipe, date, nom projet et client. Sommaire non numéroté +
2/2	QQ fautes de frappes +
2/4	Copier coller du sujet. Il faut contextualiser davantage ! +
3/4	Il manque surtout qq infos techniques sur l'appli. +
3,5/4	Attentions aux UC coupés !! Faire un UC par domaine couvert :  gestion des comptes, des clients, des crédits par ex. +
3/4	Il manque les lg et outils imposés ainsi que les règles organisationnelles : date de livraison par ex, +
	
Total : 14/20	

== doc technique retour = Documentations technique

== Eléments obligatoires
   
- Page de garde
- Sommaire
-  Présentation de l'Application
- Répartition des fonctionnalités par programmeur (Une section qui décrit le partage du travail)

- Pas de page de garge
- Il faut dire l’objectif de l’application, qui est le clien, qui sont les utilisateurs, quelles sont les principales fonctionnalités.
- pas de répartition du tavail.

== Forme :

 Toutes les figures doivent avoir un numéro et un titre et un commentaire.


== Ressources externes :
Il faut indiquer , l’utilisation de java fx …
Il faut donc s’assurer que les postes de travail des employés possèdent une JRE 1.8 pour pouvoir faire fonctionner le .jar sans encombre. 
Voir comment lancer dans le bon environnement → IHM
Comment installer l’application pour pouvoir la maintenir : accès à la base  ...



